name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
#    - name: Install dependencies
#      run: dotnet add package Newtonsoft.Json --version 12.0.1
#    - name: Restore dependencies
#      run: dotnet restore
#    - name: Build
#      run: dotnet build --no-restore
#    - name: Build
#      run: dotnet msbuild
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: RunMyWebAppDLL
      run: dotnet run bin\Debug\net5.0\myWebApp.dll
    - name: Package
      run: dotnet pack --configuration Release
    - name: AddSource
      run: dotnet nuget add source "https://nuget.pkg.github.com/tamilselvansellamuthu/index.json" -n "github"
    - name: Push
      run: dotnet nuget push "bin/Release/myWebApp.1.0.0.nupkg"  --api-key ${{ secrets.TOKEN_GITHUB }} --source "github"
